### ISSUE TITLE
cleanup github and make release

### ISSUE THREAD

**Issue by zhou13** [ashi009/bestroutetb#10]
I found that many files on github is redundant, i.e. they are generate by the script.  Could please delete them so that we can discriminate the data and script easily?  This can also make distro packager happier.

Also could you make a release like version 1.0 or 0.0.1 alpha?

**Comment by zhou13** [comment]
Also, for convenience, you can just _release_ the router table such as `routes-us` as a complement.

**Comment by ashi009** [comment]
Thanks for the advice.  But I'm afraid I won't do so. 

Currently there are only two generated files (`routes` and `routes-us`) in the repo, and it's pretty convenience for those who simply want to use the route table without typing any command.

Releasing pre-generated route tables needs to open another repo to tag it separately, and I have to revise updating scripts, which sounds like to fix something not broken.

I'll keep it unchanged until next script update.
