### ISSUE TITLE
use iproute 2 batch mode to speed up.

### ISSUE THREAD

**Issue by zhou13** [ashi009/bestroutetb#11]
See comments：http://www.solidot.org/story?sid=32486

Refer to https://github.com/jimmyxu/chnroutes

Example：

```
#!/bin/bash -

ip -batch - <<EOF
route add 1.0.1.0/24 $OLDGW
route add 1.0.2.0/23 $OLDGW
route add 1.0.8.0/21 $OLDGW
EOF
```

**Comment by ashi009** [comment]
It's already supported. check out [格式化规则文件](https://github.com/ashi009/bestroutetb/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#-4)
