### ISSUE TITLE
关于routes-us的线路疑问

### ISSUE THREAD

**Issue by justry** [ashi009/bestroutetb#12]
首先很喜欢你的这个项目！
你在使用说明中注释道：routes-us是只将美国地址路由到 VPN网关的路由表。
可是我看这张路由表却是把筛选出的IP路由到net_gateway的正常连接，表面的目的是让国内的地址走本地net，其他的地址走vpn，这样的话就不止是你说明中说的那样“只是将美国地址路由到VPN”。不知我的表诉你弄明白了没有。。。
就是说，如果按照你注释说明的那样，就得把美国的IP筛选出来并路由到vpn-gataway。
而且我感觉对于openvpn可以更精简的啊，可以把openvpn设为默认网卡，所有流量都走vpn，然后做黑名单，只把国内的IP筛选出来路由到net_gataway；或者不替换默认网卡，用route-nopull参数禁止所有流量走vpn，然后设白名单，把国外(北美)被墙的IP路由到vpn-getaway。
我不是专业IT人士，只是自己喜欢研究一下，很多东西都不懂，如果有说错的地方还请包涵。。。

**Comment by ashi009** [comment]
谢谢回复。引用说明中的内容回答你的问题。

> 这一项目旨在生成最小化的路由表，同时确保这一路由表将一部分地址路由到默认网关， 另一部分地址路由到VPN网关。

因此 `routes-us` 会保证美国地址使用 VPN 网关，中国地址使用默认网关，其余地址按照 **路由表最小化** 原则分配给二者之一。

而基于这样的原则，将0.0.0.0/0指定给默认路由可以让路由表最小。

> 若想了解更多，请查看[翻墙 VPN 本地路由表的优化](http://ashi009.tumblr.com/post/36581070478/vpn)。
