### ISSUE TITLE
iptables support possible?

### ISSUE THREAD

**Issue by luginbash** [ashi009/bestroutetb#15]
Hi there,

I've been using this route table for quite a long time, with openvpn.

Now I'm switching to iptables with transparent proxy, it would be wonderful if it's possible to use these scripts to generate iptable rules. 

Regards,

Quan Zhou.

**Comment by ashi009** [comment]
Hi,

I'm unfamiliar with iptable rules. formatter.js provided some fundamental formatting utils and customization features. Have you checked out the [formatting section](https://github.com/ashi009/bestroutetb#formatting-a-rules-file) in readme and the [example](https://github.com/ashi009/bestroutetb/wiki/PPP-on-OpenWRT)?

Please let me know if it works for you.

Best,
Xiaoyi

**Comment by luginbash** [comment]
Thanks for telling, I've edited formatter.js to work with iptables.

Works good for me.

On Sun, Nov 10, 2013 at 8:49 AM, Xiaoyi notifications@github.com wrote:

> Hi,
> 
> I'm unfamiliar with iptable rules. formatter.js provided some fundamental
> formatting utils and customization features. Have you checked out the formatting
> section https://github.com/ashi009/bestroutetb#formatting-a-rules-filein readme and the
> example https://github.com/ashi009/bestroutetb/wiki/PPP-on-OpenWRT?
> 
> Please let me know if it works for you.
> 
> Best,
> Xiaoyi
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ashi009/bestroutetb/issues/15#issuecomment-28140858
> .

## 

--.- ..- .- -.    --.. .... --- ..-
Quan Zhou
Key == ‘2E31C416E2732AAD'
--.- ..- .- -.    --.. .... --- ..-
