### ISSUE TITLE
不知所谓。描述的乱七八糟。一点都看不明白。

### ISSUE THREAD

**Issue by jangsanchoi** [ashi009/bestroutetb#18]
不知所谓。描述的乱七八糟。一点都看不明白。

要是英语描述的不清楚，还可以理解。连中文都会这样？？

**Comment by ashi009** [comment]
你需要什么帮助？

**Comment by luginbash** [comment]
我觉得描述的很清楚，基本上是标准的说明方法。

OP, please be specific, provide a helpful feed back.
—
