### ISSUE TITLE
部分中国ip默认路由是vpn_gateway

### ISSUE THREAD

**Issue by nosecrain** [ashi009/bestroutetb#2]
www.onlinedown.net[218.93.203.240]
www.189.cn[118.85.207.18]
稍后我再测试下，更新

**Comment by ashi009** [comment]
没有重现你的问题

root@OpenWrt:~# traceroute 218.93.203.240
traceroute to 218.93.203.240 (218.93.203.240), 30 hops max, 38 byte packets
 1  125.33.216.1 (125.33.216.1)  20.433 ms  23.245 ms  28.457 ms
 2  61.148.90.105 (61.148.90.105)  15.893 ms  14.788 ms  16.547 ms
root@OpenWrt:~# traceroute 118.85.207.18
traceroute to 118.85.207.18 (118.85.207.18), 30 hops max, 38 byte packets
 1  125.33.216.1 (125.33.216.1)  24.978 ms  25.740 ms  25.699 ms
 2  61.148.90.29 (61.148.90.29)  16.157 ms  15.702 ms  16.418 ms
