### ISSUE TITLE
很认真的看了你的说明，很混乱

### ISSUE THREAD

**Issue by bao3** [ashi009/bestroutetb#20]
不知道你写这个说明的时候的逻辑是怎样，反正对于想是用的人来说，完全无从下手。我就说一下我关心的几个问题：

1 任何route table生成时，是否可以不用指定什么gw,vpn_gw，就只是简单的一个route table？因为不见得我们来这里都是是用VPN的。

2 能否只是简单的生成一个国内的route  table？

**Comment by karlcheong** [comment]
只需要單純的route table 干嘛不用 chnroute....
