### ISSUE TITLE
说明内容有必要英文吗？

### ISSUE THREAD

**Issue by 512vincent** [ashi009/bestroutetb#21]
难道老外也要翻墙来墙内？

**Comment by bao3** [comment]
@3shao 我也很奇怪，这是写给英语人士看的吗？好好的东西，就不能写点人话。

**Comment by ashi009** [comment]
@3shao 这个算法并不是专门为了翻墙准备的，而可以用在更多场合，pr里边也有人将它做了一般化而可以用在多网关（≥3）的情况下。
@bao3 页面上同样有中文说明，而且写着“使用说明”。
