### ISSUE TITLE
请问如何生成 CN 网段走 net 其余都走 vpn 的路由规则？

### ISSUE THREAD

**Issue by KyonLi** [ashi009/bestroutetb#22]
仔细看过了使用说明，貌似只能设置哪些国家网段走 net 哪些走 vpn，不能只设置走 net 的网段，请问能提供这样的功能或告知正确的使用方法吗？谢谢

**Comment by ashi009** [comment]
算法设计的核心就是通过将网段二分化来生成最优的路由表，相反只设置其一就无法进行有效的优化，比如你只写 `--net=cn`，那么按照算法只会给你提供 0.0.0.0/0 使用 net 的一条规则。

**Comment by KyonLi** [comment]
原来是这样，多谢解答 ^_^

**Comment by ashi009** [comment]
不客气 : )
