### ISSUE TITLE
bestroutetb有没有一个参数可以让生成的路由表只走vpn的

### ISSUE THREAD

**Issue by agassiyzh** [ashi009/bestroutetb#24]
我来说一下我的需求啊：

最近手机在使用思科AnyConnect翻墙。server端用的是开源的ocserv。这套解决方案允许server把路由下放给手机，在客户端上就能判断哪些ip段需要翻墙。

它的配置文件是这么写的：

``` conf
route = 54.0.0.0/255.128.0.0
route = 54.128.0.0/255.192.0.0
...
```

下放的这些路由表中的ip段就是需要通过VPN链接的，配置中并不能指定哪些走本地哪些走vpn。

所以我想问一下您写的这个工具有没有提供这样一个参数，让生成的路由表都是走vpn的。

不甚感激！

**Comment by ashi009** [comment]
这个算法可行就是因为可以二分化处理，如果只能设置一方就不好用了。

On Sunday, November 23, 2014, Agassi notifications@github.com wrote:

> 我来说一下我的需求啊：
> 
> 最近手机在使用思科AnyConnect翻墙。server端用的是开源的ocserv。这套解决方案允许server把路由下放给手机，在客户端上就能判断哪些ip段需要翻墙。
> 
> 它的配置文件是这么写的：
> 
> route = 54.0.0.0/255.128.0.0
> route = 54.128.0.0/255.192.0.0
> ...
> 
> 下放的这些路由表中的ip段就是需要通过VPN链接的，配置中并不能指定哪些走本地哪些走vpn。
> 
> 所以我想问一下您写的这个工具有没有提供这样一个参数，让生成的路由表都是走vpn的。
> 
> 不甚感激！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ashi009/bestroutetb/issues/24.

## 

Sent from Gmail Mobile

**Comment by agassiyzh** [comment]
THX

**Comment by ashi009** [comment]
但是有一点你可以尝试，把生成的本地部分变成你手机的静态路由，vpn部分由服务器推送

On Sunday, November 23, 2014, Agassi notifications@github.com wrote:

> THX
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ashi009/bestroutetb/issues/24#issuecomment-64108663.

## 

Sent from Gmail Mobile

**Comment by agassiyzh** [comment]
谢谢回头试试看

-- 
Gmail
Sent with Airmail

在 2014年11月23日 14:46:19, Xiaoyi (notifications@github.com) 写到:

但是有一点你可以尝试，把生成的本地部分变成你手机的静态路由，vpn部分由服务器推送
