### ISSUE TITLE
bestroutetb 得到的檔案怎麼使用，放在那裡呢？

### ISSUE THREAD

**Issue by Joney0210** [ashi009/bestroutetb#29]
環境 OS X 10.10.3
設備 rMBP 2013 later

本人小白一個，仔細看過並嘗試之後，發現我完全不了解怎麼使用下完指令後生成的檔案？ 
放在 /etc/ppp 中也沒有作用。

在Google大神也拒絕幫忙後，只好來求助了。
誠心燒香以求過路大神的幫助。

問題其實是怎麼生成OSX 可以放在/etc/ppp中使用的檔案？如chnroute中一樣？
若使用方式不是這樣，那麼應該怎麼做？

PS：試過自行修改檔案，配合chnroute ip-up 中的格式。可是生成的檔案中包含了黑白名單，而chnroute中的格式只有白名單，於是放棄。

**Comment by pi1ot** [comment]
same question.

**Comment by ashi009** [comment]
我会在下周内测试一下，然后更新文档。

**Comment by pi1ot** [comment]
@ashi009 we are waiting...

**Comment by ashi009** [comment]
不好意思。。。最近太忙，周末一定更新文档

**Comment by ashi009** [comment]
半成品：https://github.com/ashi009/bestroutetb/wiki/OS-X-下的-PPP-ip-up-配置

**Comment by pi1ot** [comment]
多谢
