### ISSUE TITLE
想把美国的IP地址段弄成200条路由指令，怎么做？

### ISSUE THREAD

**Issue by wang20150419** [ashi009/bestroutetb#37]
这有的话，ocserv服务器就可以只针对美国地址翻墙了。

按 bestroutetb --route.vpn=us -p json -o routes.json 这个得到
的IP地址段，是从45.127.64.0 开始的，明显有好多美国地址不在里面。

**Comment by ashi009** [comment]
https://github.com/ashi009/bestroutetb/blob/npm/README.zh.md
