### ISSUE TITLE
只route中国路由 其他路由default?

### ISSUE THREAD

**Issue by hlx98007** [ashi009/bestroutetb#38]
我用的这个命令（命令行版本）

```bash
./cli.js --route.net=0.0.0.0/0 \
          --route.vpn=cn \
          -p iproute \
          -o ~/route \
          --gateway.net=192.168.9.1 \
          --gateway.vpn=192.168.168.2
```

出来的up.sh为
```
#!/bin/sh
ip -b - <<FILE
r a 0.0.0.0/0 via 192.168.9.1
r a 0.0.0.0/1 via 192.168.168.2
r a 128.0.0.0/1 via 192.168.168.2
FILE
```

不知道是不是我的命令错了还是什么，我需要国外的某台服务器访问国内时走另外一台跳板去国内。这个脚本是不是默认自己是位于中国了？

如何构建我所需求的命令？

**Comment by ashi009** [comment]
只路由中国地址其他default不是一个有效的用例：

> chnroutes 会生成一个将全部中国子网路由到 ISP 网关的， 并将其它地址路由到 VPN 网关的路由表。而本项目将 IP 地址分成三组。 第一组被保证路由到 ISP 网关，第二组被保证路由到 VPN 网关。 与此同时，最后一组将会被动态的分配到其中一个网关，使产生的 路由表最小。

`--route.net=0.0.0.0/0`虽然是全部地址，但是 cn 也包含在里边，并不满足使用条件。
