### ISSUE TITLE
IP表不准确？

### ISSUE THREAD

**Issue by snnn** [ashi009/bestroutetb#6]
140.211.11.131 这个IP明明是美国的，但是却没有通过vpn gateway访问。
经查data中有这样一条
delegated-apnic-latest:apnic|ID|ipv4|140.0.0.0|65536|20110330|allocated

**Comment by ashi009** [comment]
按照ip表，这一个ip块是属于印尼的 apnic|ID|ipv4|140.0.0.0|65536|20110330|allocated，另外这个范围只覆盖到140.0.255.255，所以你给的ip我再查查

**Comment by ashi009** [comment]
140.211.0.0/16不在APNIC的管域，所以没有出现在APNIC的分配表里。虽然它属于ARIN，但是由于没有ARIN的详细分配表，只有/24级别的分配表，所以在产生规则时也就没有人声明对它负责，因此被划分为默认网关。

可以在生成规则时加上这条规则`--vpn=144.211.0.0/16,us`

**Comment by ashi009** [comment]
新版本已经添加了ARIN源，问题应该已经解决
