### ISSUE TITLE
请求添加教育网免费IP网段

### ISSUE THREAD

**Issue by Mutinux** [ashi009/bestroutetb#8]
感谢您写出这么好的工具。
我在教育网，希望能增加教育网免费IP网段，使其走本地路由而非OPENVPN，具体IP段见下链接：
http://www.nic.edu.cn/RS/ipstat/internalip/real.html
再次感谢！

**Comment by ashi009** [comment]
您所给的url从公网不能访问 请帖一份在这里吧
在 2013-5-19 下午4:01，"Mutinux" notifications@github.com写道：

**Comment by Mutinux** [comment]
http://jianguoyun.com/p/Deg1xjcQxQsY3kI
挺长的，怕贴不对，我把这个网页下下来了，见上面链接。再次感谢！

**Comment by ashi009** [comment]
据我猜测，这个的效果恐怕不会好。这个算法起作用的基础是归并中间的“灰色地带”（比如中国地址走默认网关，美国地址走vpn网关，其余地址随意，其余地址就是灰色地带），从而减小路由条目数量。但是按你的需求这个灰色地带是不存在的，所以可能合并效果十分的有限。

**Comment by Mutinux** [comment]
似乎确如您所说，这个列表相当于一个白名单了。看起来也不必麻烦这一把了。。。

## 

Mutinux Lau

School and Hospital of Stomatology
Peking University

在 2013年5月19日星期日，下午10:29，Xiaoyi 写道：
