### ISSUE TITLE
能不能按域名实现最小路由?

### ISSUE THREAD

**Issue by zhfish** [ashi009/bestroutetb#9]
已知常用需要翻墙的域名不到10个,把每个域名的ip都搞全,应该也没有多少吧?
比如google,twitter,facebook,wordpress等等

整个欧美的范围太大了,希望可以有真正的最小路由
翻墙的大都不怕折腾,如果遇到哪个被墙了非看不可,自己添加就是..

**Comment by ashi009** [comment]
做不到。这个要求对bestroutetb没有问题，但是没法收集这些域名对应的IP地址。
